apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-duplo
  name: pod-duplo
spec:
  containers:
  - image: nginx
    name: nginx
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600" 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always