apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-emptydir
  name: pod-emptydir
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /pod-empytdir
      name: primeiro-empytdir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-empytdir
    emptyDir:
      sizeLimit: 256Mi