apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-girus
  name: nginx-girus
  namespace: nginx-girus
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-girus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-girus
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx-girus
        resource:
          limits:
            cpu: "0.3"
            memory: 128Mi
          requests:
            cpu: "0,1"
            memory: 64Mi